import { ApiProperty } from '@nestjs/swagger';

export class UserDto {
  @ApiProperty({ description: 'User unique autogenerated ID' })
  id!: string;

  @ApiProperty({ example: 'maya@example.com' })
  email!: string;
}
